routes/web.php
<?php
Route::get('/', 'HomeController@index')->name('main');

Route::get('ticket/{id}', ['as' => 'home.view','uses' =>'HomeController@view']);
Route::post('ticket/{id}', ['as' => 'home.reply','uses' =>'HomeController@reply']);

Route::get('faq', ['as' => 'faq','uses' =>'HomeController@faq']);
Route::get('search', ['as' => 'search','uses' =>'HomeController@search']);
Route::post('search', ['as' => 'ticket.search','uses' =>'HomeController@ticketSearch']);


Route::name('admin.')->prefix('admin')->middleware('auth')->group(function() {
    Route::get('dashboard', 'DashboardController')->name('dashboard');

    Route::get('users/roles', 'UserController@roles')->name('users.roles');
    Route::resource('users', 'UserController', [
        'names' => [
            'index' => 'users'
        ]
    ]);
    Route::get('lang/clear',['as' => 'lang.clear','uses' =>'LanguageController@clear']);

    Route::get('lang/create',['as' => 'lang.create','uses' =>'LanguageController@create']);
    Route::post('lang/create',['as' => 'lang.store','uses' =>'LanguageController@store']);
    Route::get('lang/{lang}',['as' => 'lang.index','uses' =>'LanguageController@index']);
    Route::post('lang/{lang}',['as' => 'lang.store.data','uses' =>'LanguageController@storeData']);

    Route::get('lang/change/{lang}',['as' => 'lang.update','uses' =>'LanguageController@update']);

    Route::get('ticket/create',['as' => 'tickets.create','uses' =>'TicketController@create']);
    Route::post('ticket',['as' => 'tickets.store','uses' =>'TicketController@store']);
    Route::get('ticket/{status?}',['as' => 'tickets.index','uses' =>'TicketController@index']);
    Route::get('ticket/{id}/edit',['as' => 'tickets.edit','uses' =>'TicketController@editTicket']); //escalate
    Route::get('ticket/{id}/escalate',['as' => 'tickets.escalate','uses' =>'TicketController@escalateTicket']); //escalate
    Route::delete('ticket/{id}/destroy',['as' => 'tickets.destroy','uses' =>'TicketController@destroy']);
    Route::delete('ticket-attachment/{tid}/destroy/{id}',['as' => 'tickets.attachment.destroy','uses' =>'TicketController@attachmentDestroy']);
    Route::put('ticket/{id}/update',['as' => 'tickets.update','uses' =>'TicketController@updateTicket']);

    Route::get('category/create',['as' => 'category.create','uses' =>'CategoryController@create']);
    Route::post('category',['as' => 'category.store','uses' =>'CategoryController@store']);
    Route::get('category',['as' => 'category','uses' =>'CategoryController@index']);
    Route::get('category/{id}/edit',['as' => 'category.edit','uses' =>'CategoryController@edit']);
    Route::delete('category/{id}/destroy',['as' => 'category.destroy','uses' =>'CategoryController@destroy']);
    Route::put('category/{id}/update',['as' => 'category.update','uses' =>'CategoryController@update']);

    Route::get('faq/create',['as' => 'faq.create','uses' =>'FaqController@create']);
    Route::post('faq',['as' => 'faq.store','uses' =>'FaqController@store']);
    Route::get('faq',['as' => 'faq','uses' =>'FaqController@index']);
    Route::get('faq/{id}/edit',['as' => 'faq.edit','uses' =>'FaqController@edit']);
    Route::delete('faq/{id}/destroy',['as' => 'faq.destroy','uses' =>'FaqController@destroy']);
    Route::put('faq/{id}/update',['as' => 'faq.update','uses' =>'FaqController@update']);

//    Route::('category',['as' => 'category','uses' =>'CategoryController@index']);
    Route::post('ticket/{id}/conversion',['as' => 'conversion.store','uses' =>'ConversionController@store']);
    Route::post('ticket/{id}/note',['as' => 'note.store','uses' =>'TicketController@storeNote']);

    Route::get('setting',['as' => 'setting','uses' =>'UserController@setting']);
    Route::post('setting',['as' => 'setting.store','uses' =>'UserController@save_setting']);

    Route::get('business_units',['as' => 'buss_units','uses' =>'bussUnitsController@buss_units']);

    Route::post('ticket/{id}/update_escalation',['as' => 'escalation.update','uses' =>'TicketController@update_escalation']);

    Route::get('channel-report',['as' => 'report.channel','uses' =>'ReportController@channelShow']);
    Route::get('category-report',['as' => 'report.category','uses' =>'ReportController@categoryShow']);

    Route::post('channel-check',['as' => 'report.check','uses' =>'ReportController@checkChannel']);
    Route::post('category-check',['as' => 'report.catcheck','uses' =>'ReportController@checkCategory']);
    // Message Route
    Route::get('chat',['as' => 'chats','uses' =>'MessageController@index']);
    Route::get('message/{id}',['as' => 'message','uses' => 'MessageController@getMessage']);
    Route::post('message', 'MessageController@sendMessage');
    // End Message Route

});

Route::get('home', ['as' => 'home','uses' =>'HomeController@index']);

Route::prefix('sbu/sbu-ref={sbu_id}/')->group(function () {

    Route::get('home', ['as' => 'home','uses' =>'HomeController@new_ticket_index']);
    Route::post('home', ['as' => 'home.store','uses' =>'HomeController@store']);
    });

Route::get('get_message',['as' => 'get_message','uses' => 'MessageController@getFloatingMessage']);
Route::post('message_form',['as' => 'chat_form.store','uses' =>'MessageController@store']);
Route::post('floating_message', 'MessageController@sendFloatingMessage');

Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Auth::routes(['verify' => true]);

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable = [
        'ticket_id','name', 'email', 'category','subject','status','description','attachments','note','sbu_id','phone','idno','gender','acc_number','branch',
        'qualification','issue_escalation_level','issue_escalated_to','must_close_at','channel'
    ];

    public function conversions(){
        return $this->hasMany('App\Conversion','ticket_id','id')->orderBy('id');
    }

    public function ticket_assignee(){
        return $this->hasOne('App\User', 'id', 'issue_escalated_to');
    }

    public function ticket_level(){
        return $this->hasOne('App\EscalationGroup', 'id', 'issue_escalation_level');
    }




}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Mail\SendTicket;
use App\Ticket;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($status = '')
    {
        $user = \Auth::user();
        if($user->can('manage-tickets'))
        {
            $tickets = Ticket::select(
                [
                    'tickets.*',
                    'categories.name as category_name',
                    'categories.color',
                ]
            )->join('categories', 'categories.id', '=', 'tickets.category');
            if($status == 'in-progress')
            {
                $tickets->where('status', '=', 'In Progress');
            }
            elseif($status == 'on-hold')
            {
                $tickets->where('status', '=', 'On Hold');
            }
            elseif($status == 'closed')
            {
                $tickets->where('status', '=', 'Closed');
            }
            $tickets = $tickets->get();

            return view('admin.tickets.index', compact('tickets'));
        }
        else
        {
            return view('403');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = \Auth::user();
        if($user->can('create-tickets'))
        {
            $categories = Category::get();

            return view('admin.tickets.create', compact('categories'));
        }
        else
        {
            return view('403');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = \Auth::user();
        if($user->can('create-tickets'))
        {

            $validation = [
                'name' => [
                    'required',
                    'string',
                    'max:255',
                ],
                'email' => [
                    'required',
                    'string',
                    'email',
                    'max:255',
                ],
                'category' => [
                    'required',
                    'string',
                    'max:255',
                ],
                'subject' => [
                    'required',
                    'string',
                    'max:255',
                ],
                'status' => [
                    'required',
                    'string',
                    'max:100',
                ],
                'description' => ['required'],
            ];
            if($request->hasfile('attachments'))
            {
                $validation['attachments.*'] = 'mimes:doc,pdf,docx,zip,png,jpeg,jpg';
            }
            $this->validate($request, $validation);

            $post              = $request->all();
            $post['ticket_id'] = time();
            $post['channel'] = 'Web';

            $data              = [];
            if($request->hasfile('attachments'))
            {
                foreach($request->file('attachments') as $file)
                {
                    $name = $file->getClientOriginalName();
                    $file->move(storage_path() . '/tickets/' . $post['ticket_id'] . "/", $name);
                    $data[] = $name;
                }
            }
            $post['attachments'] = json_encode($data);
            $ticket              = Ticket::create($post);


            // Send Email to User
            try
            {
                Mail::to($ticket->email)->send(new SendTicket($ticket));
            }
            catch(\Exception $e)
            {
                $error_msg = "E-Mail has been not sent due to SMTP configuration ";
            }

            // Send Email to
            if(isset($error_msg))
            {
                Session::put('smtp_error', '<span class="text-danger">' . $error_msg . '</span>');
            }
            Session::put('ticket_id', ' <a class="text text-white" href="' . route('home.view', \Illuminate\Support\Facades\Crypt::encrypt($ticket->ticket_id)) . '"><b>' . __('Your unique ticket link is this.') . '</b></a><br><br> ');

            // return redirect()->back()->with('success', __('Ticket created successfully') . ' <a href="' . route('home.view', \Illuminate\Support\Facades\Crypt::encrypt($ticket->ticket_id)) . '"><b>' . __('Your unique ticket link is this.') . '</b></a> ' . ((isset($error_msg)) ? '<br> <span class="text-danger">' . $error_msg . '</span>' : ''));
            return redirect()->route('admin.tickets.index')->with('success', __('Ticket created successfully'));
        }
        else
        {
            return view('403');
        }
    }

    public function storeNote($ticketID, Request $request)
    {
        $user = \Auth::user();
        if($user->can('reply-tickets'))
        {
            $validation = [
                'note' => ['required'],
            ];
            $this->validate($request, $validation);

            $ticket = Ticket::find($ticketID);
            if($ticket)
            {
                $ticket->note = $request->note;
                $ticket->save();

                return redirect()->back()->with('success', __('Ticket note saved successfully'));
            }
            else
            {
                return view('403');
            }
        }
        else
        {
            return view('403');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Ticket $ticket
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Ticket $ticket
     *
     * @return \Illuminate\Http\Response
     */
    public function editTicket($id)
    {
        $user = \Auth::user();
        if($user->can('edit-tickets'))
        {
            $ticket = Ticket::find($id);
            if($ticket)
            {
                $categories = Category::get();

                return view('admin.tickets.edit', compact('ticket', 'categories'));
            }
            else
            {
                return view('403');
            }
        }
        else
        {
            return view('403');
        }
    }

    public function escalateTicket($id)
    {
        $user = \Auth::user();
        if($user->can('edit-tickets'))
        {
            $ticket = Ticket::find($id);
            $ticket_sbu = $ticket->sbu_id;
            $curr_esc_lev = $ticket->issue_escalation_level;
            if($ticket)
            {
                $categories = Category::get();
                $escalate_resource = User::where('sbu_id',$ticket_sbu)
                                            ->where('escalation_levels','>',$curr_esc_lev)
                                            ->get();
                return view('admin.tickets.escalate', compact('ticket', 'categories','escalate_resource'));
            }
            else
            {
                return view('403');
            }
        }
        else
        {
            return view('403');
        }
    }

    public function update_escalation(Request $request,$ticket_id){
        $user = \Auth::user();

        $validation = [
            'issue_escalated_to' => [
                'required',
                'integer',
                'max:255',
            ]
        ];

        $this->validate($request, $validation);
                $post = $request->all();


                $user = User::find($post['issue_escalated_to']);
                $esc_level = $user->escalation_levels;
                $name = $user->name;
                $ticket = Ticket::find($ticket_id);
                $post['issue_escalation_level'] = $esc_level;

                $ticket->update($post);

                return redirect()->back()->with('success', __('Ticket has been successfully escalated to '.$name));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Ticket $ticket
     *
     * @return \Illuminate\Http\Response
     */
    public function updateTicket(Request $request, $id)
    {
        $user = \Auth::user();
        if($user->can('edit-tickets'))
        {
            $ticket = Ticket::find($id);
            if($ticket)
            {
                $validation = [
                    'name' => [
                        'required',
                        'string',
                        'max:255',
                    ],
                    'email' => [
                        'required',
                        'string',
                        'email',
                        'max:255',
                    ],
                    'category' => [
                        'required',
                        'string',
                        'max:255',
                    ],
                    'subject' => [
                        'required',
                        'string',
                        'max:255',
                    ],
                    'status' => [
                        'required',
                        'string',
                        'max:100',
                    ],
                    'description' => ['required'],
                ];
                if($request->hasfile('attachments'))
                {
                    $validation['attachments.*'] = 'mimes:doc,pdf,docx,zip,png,jpeg,jpg';
                }
                $this->validate($request, $validation);

                $post = $request->all();

resources/views/admin/tickets/edit.blade.php
@extends('layouts.admin-master')

@section('title')
    {{ __('Reply Ticket') }} - {{ $ticket->ticket_id }}
@endsection
@section('scripts')
    <script src="//cdn.ckeditor.com/4.12.1/basic/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('description');
        CKEDITOR.replace('reply_description');
        CKEDITOR.replace('note');
    </script>
@endsection

@section('breadcrumb')
    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i> {{ __('Dashboard') }}</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.tickets.index') }}">{{ __('Manage Ticket') }}</a></li>
        {{-- <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>--}}
    </ol>
@endsection

@section('actions')
    @can('edit-tickets')
        <button class="btn btn-sm btn-neutral" type="button" data-toggle="collapse" href="#ticket-info"><i class="fa fa-edit"></i> {{ __('Action Ticket') }}</button>
<a class="btn btn-sm btn-danger"  href="{{route('admin.tickets.escalate',$ticket->id)}}"><i class="fa fa-arrow-up"></i> {{ __('Escalate Ticket') }}</a>
    @endcan
@endsection

@section('content')
    @can('edit-tickets')
        <form class="collapse" id="ticket-info" action="{{route('admin.tickets.update',$ticket->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-header"><h4>{{ __('Ticket Information') }}</h4></div>
                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="require form-control-label">{{ __('Name') }}</label>
                                    <input class="form-control" type="text" name="name" required="" value="{{ $ticket->name }}">
                                    <div class="invalid-feedback">
                                        {{ $errors->first('name') }}
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="require form-control-label">{{ __('Email') }}</label>
                                    <input class="form-control" type="email" name="email" required="" value="{{ $ticket->email }}">
                                    <div class="invalid-feedback">
                                        {{ $errors->first('email') }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="require form-control-label">{{ __('Category') }}</label>
                                    <select class="form-control select2" name="category" required="">
                                        <option value="">{{ __('Select Category') }}</option>
                                        @foreach($categories as $category)
                                            <option value="{{$category->id}}" @if($ticket->category == $category->id) selected @endif>{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                    <div class="invalid-feedback">
                                        {{ $errors->first('category') }}
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="require form-control-label">{{ __('Status') }}</label>
                                    <select class="form-control select2" name="status" required="">
                                        <option value="In Progress" @if($ticket->status == 'In Progress') selected @endif>{{ __('In Progress') }}</option>
                                        <option value="On Hold" @if($ticket->status == 'On Hold') selected @endif>{{ __('On Hold') }}</option>
                                        <option value="Closed" @if($ticket->status == 'Closed') selected @endif>{{ __('Closed') }}</option>
                                    </select>
                                    <div class="invalid-feedback">
                                        {{ $errors->first('status') }}
                                    </div>
                                </div>

                                <div class="form-group col-md-12">
                                    <label class="require form-control-label">{{ __('Subject') }}</label>
                                    <input class="form-control" type="text" name="subject" required="" value="{{ $ticket->subject }}">
                                    <div class="invalid-feedback">
                                        {{ $errors->first('subject') }}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="require form-control-label">{{ __('Description') }}</label>
                                <textarea name="description" class="form-control">{{ $ticket->description }}</textarea>
                                <div class="invalid-feedback">
                                    {{ $errors->first('description') }}
                                </div>
                            </div>
                        </div>
                        <footer class="card-footer text-right">
                            <a class="btn btn-secondary mr-2" href="{{route('admin.tickets.index')}}">{{ __('Cancel') }}</a>
                            <button class="btn btn-primary" type="submit">{{ __('Update') }}</button>
                        </footer>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card">
                        <div class="card-header"><h4>{{ __('Attachments') }}</h4></div>
                        <div class="card-body">
                            <div class="input-group file-group">
                                <input type="file" multiple="" name="attachments[]" class="form-control">
                                <div class="invalid-feedback">
                                    {{ $errors->first('attachments') }}
                                </div>
                            </div>
                            <div class="m-1">
                                <ul class="list-group list-group-flush">
                                    @php
                                        $attachments=json_decode($ticket->attachments);
                                    @endphp
                                    @foreach($attachments as $index => $attachment)
                                        <li class="list-group-item">
                                            {{$attachment}}<a download="" href="{{ env('APP_URL').Storage::url('tickets/'.$ticket->ticket_id."/".$attachment)}}" class="btn btn-outline-primary ml-1 p-2" title="{{ __('Download') }}"><i class="fa fa-download"></i></a>
                                            <a class="text-danger ml-1" title="Delete" onclick="(confirm('Are You Sure?')?(document.getElementById('user-form-{{$index}}').submit()):'');"><i class="nav-icon i-Close-Window font-weight-bold"></i></a>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        @foreach($attachments as $index => $attachment)
            <form method="post" id="user-form-{{$index}}" action="{{route('admin.tickets.attachment.destroy',[$ticket->id,$index])}}">
                @csrf
                @method('DELETE')
            </form>
        @endforeach
    @endcan
    <br><br>
    <div class="row">

        <div class="col-8">

            <div class="card">
                <div class="card-header"><h4>{{$ticket->name}} <small><small>{{$ticket->created_at->diffForHumans()}}</small></small></h4></div>
                <div class="card-body">
                    <div>{!! $ticket->description !!}</div>
                    @php
                        $attachments=json_decode($ticket->attachments);
                    @endphp
                    @if(count($attachments))
                        <div class="m-1">
                            <b>{{ __('Attachments') }} :</b>
                            <ul class="list-group list-group-flush">
                                @foreach($attachments as $index => $attachment)
                                    <li class="list-group-item">
                                        {{$attachment}}<a download="" href="{{ env('APP_URL').Storage::url('tickets/'.$ticket->ticket_id."/".$attachment)}}" class="btn btn-outline-primary ml-1 p-2" title="{{ __('Download') }}"><i class="fa fa-download"></i></a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
            <br>

            @foreach($ticket->conversions as $conversion)
                <div class="card">
                    <div class="card-header"><h4>{{$conversion->replyBy()->name}} <small><small>{{$conversion->created_at->diffForHumans()}}</small></small></h4></div>
                    <div class="card-body">
                        <div>{!! $conversion->description !!}</div>
                        @php
                            $attachments=json_decode($conversion->attachments);
                        @endphp
                        @if(count($attachments))
                            <div class="m-1">
                                <b>Attachments :</b>
                                <ul class="list-group list-group-flush">
                                    @foreach($attachments as $index => $attachment)
                                        <li class="list-group-item">
                                            {{$attachment}}<a download="" href="{{ env('APP_URL').Storage::url('tickets/'.$ticket->ticket_id."/".$attachment)}}" class="btn btn-outline-primary ml-1 p-2" title="{{ __('Download') }}"><i class="fa fa-download"></i></a>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>
                </div>
                <br>
            @endforeach
        </div>
        @can('reply-tickets')
            <div class="col-4">
                <div class="card">
                    <div class="card-header"><h4>{{ __('Add Reply') }}</h4></div>
                    <form method="post" action="{{route('admin.conversion.store',$ticket->id)}}" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">

                            <div class="form-group">
                                <label class="require form-control-label">{{ __('Description') }}</label>
                                <textarea name="reply_description" class="form-control"></textarea>
                                <div class="invalid-feedback">
                                    {{ $errors->first('reply_description') }}
                                </div>
                            </div>
                            <div class="form-group file-group">
                                <label class="require form-control-label">{{ __('Attachments') }}</label>
                                <input type="file" class="form-control" multiple="" name="reply_attachments[]">
                                <div class="invalid-feedback">
                                    {{ $errors->first('reply_attachments') }}
                                </div>
                            </div>
                        </div>

                        <footer class="card-footer text-right">
                            <button class="btn btn-primary" type="submit">{{ __('Submit') }}</button>
                        </footer>
                    </form>
                </div>
                <div class="card mt-4">
                    <div class="card-header"><h4>{{ __('Note') }}</h4></div>
                    <form method="post" action="{{route('admin.note.store',$ticket->id)}}">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <textarea name="note" class="form-control">{{$ticket->note}}</textarea>
                                <div class="invalid-feedback">
                                    {{ $errors->first('note') }}
                                </div>
                            </div>
                        </div>

                        <footer class="card-footer text-right">
                            <button class="btn btn-primary" type="submit">{{ __('Add Note') }}</button>
                        </footer>
                    </form>
                </div>
            </div>
        @endcan
    </div>



@endsection