routes/web.php
<?php
Route::get('/', 'HomeController@index')->name('main');

Route::get('ticket/{id}', ['as' => 'home.view','uses' =>'HomeController@view']);
Route::post('ticket/{id}', ['as' => 'home.reply','uses' =>'HomeController@reply']);

Route::get('faq', ['as' => 'faq','uses' =>'HomeController@faq']);
Route::get('search', ['as' => 'search','uses' =>'HomeController@search']);
Route::post('search', ['as' => 'ticket.search','uses' =>'HomeController@ticketSearch']);


Route::name('admin.')->prefix('admin')->middleware('auth')->group(function() {
    Route::get('dashboard', 'DashboardController')->name('dashboard');

    Route::get('users/roles', 'UserController@roles')->name('users.roles');
    Route::resource('users', 'UserController', [
        'names' => [
            'index' => 'users'
        ]
    ]);
    Route::get('lang/clear',['as' => 'lang.clear','uses' =>'LanguageController@clear']);

    Route::get('lang/create',['as' => 'lang.create','uses' =>'LanguageController@create']);
    Route::post('lang/create',['as' => 'lang.store','uses' =>'LanguageController@store']);
    Route::get('lang/{lang}',['as' => 'lang.index','uses' =>'LanguageController@index']);
    Route::post('lang/{lang}',['as' => 'lang.store.data','uses' =>'LanguageController@storeData']);

    Route::get('lang/change/{lang}',['as' => 'lang.update','uses' =>'LanguageController@update']);

    Route::get('ticket/create',['as' => 'tickets.create','uses' =>'TicketController@create']);
    Route::post('ticket',['as' => 'tickets.store','uses' =>'TicketController@store']);
    Route::get('ticket/{status?}',['as' => 'tickets.index','uses' =>'TicketController@index']);
    Route::get('ticket/{id}/edit',['as' => 'tickets.edit','uses' =>'TicketController@editTicket']); //escalate
    Route::get('ticket/{id}/escalate',['as' => 'tickets.escalate','uses' =>'TicketController@escalateTicket']); //escalate
    Route::delete('ticket/{id}/destroy',['as' => 'tickets.destroy','uses' =>'TicketController@destroy']);
    Route::delete('ticket-attachment/{tid}/destroy/{id}',['as' => 'tickets.attachment.destroy','uses' =>'TicketController@attachmentDestroy']);
    Route::put('ticket/{id}/update',['as' => 'tickets.update','uses' =>'TicketController@updateTicket']);

    Route::get('category/create',['as' => 'category.create','uses' =>'CategoryController@create']);
    Route::post('category',['as' => 'category.store','uses' =>'CategoryController@store']);
    Route::get('category',['as' => 'category','uses' =>'CategoryController@index']);
    Route::get('category/{id}/edit',['as' => 'category.edit','uses' =>'CategoryController@edit']);
    Route::delete('category/{id}/destroy',['as' => 'category.destroy','uses' =>'CategoryController@destroy']);
    Route::put('category/{id}/update',['as' => 'category.update','uses' =>'CategoryController@update']);

    Route::get('faq/create',['as' => 'faq.create','uses' =>'FaqController@create']);
    Route::post('faq',['as' => 'faq.store','uses' =>'FaqController@store']);
    Route::get('faq',['as' => 'faq','uses' =>'FaqController@index']);
    Route::get('faq/{id}/edit',['as' => 'faq.edit','uses' =>'FaqController@edit']);
    Route::delete('faq/{id}/destroy',['as' => 'faq.destroy','uses' =>'FaqController@destroy']);
    Route::put('faq/{id}/update',['as' => 'faq.update','uses' =>'FaqController@update']);

//    Route::('category',['as' => 'category','uses' =>'CategoryController@index']);
    Route::post('ticket/{id}/conversion',['as' => 'conversion.store','uses' =>'ConversionController@store']);
    Route::post('ticket/{id}/note',['as' => 'note.store','uses' =>'TicketController@storeNote']);

    Route::get('setting',['as' => 'setting','uses' =>'UserController@setting']);
    Route::post('setting',['as' => 'setting.store','uses' =>'UserController@save_setting']);

    Route::get('business_units',['as' => 'buss_units','uses' =>'bussUnitsController@buss_units']);

    Route::post('ticket/{id}/update_escalation',['as' => 'escalation.update','uses' =>'TicketController@update_escalation']);

    Route::get('channel-report',['as' => 'report.channel','uses' =>'ReportController@channelShow']);
    Route::get('category-report',['as' => 'report.category','uses' =>'ReportController@categoryShow']);

    Route::post('channel-check',['as' => 'report.check','uses' =>'ReportController@checkChannel']);
    Route::post('category-check',['as' => 'report.catcheck','uses' =>'ReportController@checkCategory']);
    // Message Route
    Route::get('chat',['as' => 'chats','uses' =>'MessageController@index']);
    Route::get('message/{id}',['as' => 'message','uses' => 'MessageController@getMessage']);
    Route::post('message', 'MessageController@sendMessage');
    // End Message Route

});

Route::get('home', ['as' => 'home','uses' =>'HomeController@index']);

Route::prefix('sbu/sbu-ref={sbu_id}/')->group(function () {

    Route::get('home', ['as' => 'home','uses' =>'HomeController@new_ticket_index']);
    Route::post('home', ['as' => 'home.store','uses' =>'HomeController@store']);
    });

Route::get('get_message',['as' => 'get_message','uses' => 'MessageController@getFloatingMessage']);
Route::post('message_form',['as' => 'chat_form.store','uses' =>'MessageController@store']);
Route::post('floating_message', 'MessageController@sendFloatingMessage');

Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Auth::routes(['verify' => true]);

resources/views/admin/partials/footer.blade.php
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-12">
            <div class="copyright text-center text-lg-right text-muted">
                &copy; 2019 <a href="#" class="font-weight-bold ml-1">{{env('APP_NAME')}}</a> {{ __('All rights reserved') }}
            </div>
        </div>
    </div>
</footer>

resources/views/admin/partials/sidebar.blade.php
<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <div class="sidenav-header d-flex align-items-center">
            <a class="navbar-brand" href="">
                <img src="{{asset(Storage::url('app/logo.png'))}}" class="navbar-brand-img" alt="">
            </a>
            <div class="ml-auto">
                <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
                    <div class="sidenav-toggler-inner">
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-inner">
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {{ request()->is('*dashboard*') ? ' active' : '' }}" href="{{ route('admin.dashboard') }}">
                            <i class="ni ni-shop text-primary"></i>
                            <span class="nav-link-text">{{ __('Dashboard') }}</span>
                        </a>
                    </li>
                    @can('manage-users')
                        <li class="nav-item">
                            <a class="nav-link {{ request()->is('*users*') ? ' active' : '' }}" href="{{ route('admin.users') }}">
                                <i class="ni ni-single-02 text-info"></i>
                                <span class="nav-link-text">{{ __('Users') }}</span>
                            </a>
                        </li>
                    @endcan
                    <li class="nav-item">
                        <a class="nav-link {{ request()->is('*ticket*') ? ' active' : '' }}" href="#navbar-maps" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-maps">
                            <i class="ni ni-briefcase-24 text-dark"></i>
                            <span class="nav-link-text">{{ __('Ticket') }}</span>
                        </a>
                        <div class="collapse {{ request()->is('*ticket*') ? ' show' : '' }}" id="navbar-maps">
                            <ul class="nav nav-sm flex-column">
                                <li class="nav-item {{ request()->is('*ticket') ? ' active' : '' }}">
                                    <a href="{{route('admin.tickets.index')}}" class="nav-link">
                                        {{ __('All') }}
                                    </a>
                                </li>
                                <li class="nav-item {{ request()->is('*ticket/in-progress') ? ' active' : '' }}">
                                    <a href="{{route('admin.tickets.index','in-progress')}}" class="nav-link">
                                        <span class="item-name">{{ __('In Progress') }}</span>
                                    </a>
                                </li>
                                <li class="nav-item {{ request()->is('*ticket/on-hold') ? ' active' : '' }}">
                                    <a href="{{route('admin.tickets.index','on-hold')}}" class="nav-link">
                                        <span class="item-name">{{ __('On Hold') }}</span>
                                    </a>
                                </li>
                                <li class="nav-item {{ request()->is('*ticket/closed') ? ' active' : '' }}">
                                    <a href="{{route('admin.tickets.index','closed')}}" class="nav-link">
                                        <span class="item-name">{{ __('Closed') }}</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    @can('manage-category')
                        <li class="nav-item">
                            <a class="nav-link {{ request()->is('*category*') ? ' active' : '' }}" href="{{ route('admin.category') }}">
                                <i class="ni ni-archive-2 text-green"></i>
                                <span class="nav-link-text">{{ __('Category') }}</span>
                            </a>
                        </li>
                    @endcan
                    @can('manage-faq')
                        <li class="nav-item">
                            <a class="nav-link {{ request()->is('*faq*') ? ' active' : '' }}" href="{{ route('admin.faq') }}">
                                <i class="ni ni-ungroup text-orange"></i>
                                <span class="nav-link-text">{{ __('FAQ') }}</span>
                            </a>
                        </li>
                    @endcan
                    @if(env('CHAT_MODULE') == 'yes')
                        <li class="nav-item">
                            <a class="nav-link {{ request()->is('*chat*') ? ' active' : '' }}" href="{{ route('admin.chats') }}">
                                <i class="ni ni-chat-round text-primary"></i>
                                <span class="nav-link-text">{{ __('Chat') }}</span>
                            </a>
                        </li>
                    @endif
                    @can('manage-setting')
                        <li class="nav-item">
                            <a class="nav-link {{ request()->is('*setting*') ? ' active' : '' }}" href="{{ route('admin.setting') }}">
                                <i class="ni ni-settings text-red"></i>
                                <span class="nav-link-text">{{ __('Setting') }}</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {{ request()->is('*business_units*') ? ' active' : '' }}" href="{{ route('admin.buss_units') }}">
                                <i class="ni ni-books text-success"></i>
                                <span class="nav-link-text">{{ __('Business Units') }}</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link {{ request()->is('*channel-report*') ? ' active' : '' }}" href="#navbar-maps" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="navbar-maps">
                                <i class="ni ni-chart-bar-32 text-dark"></i>
                                <span class="nav-link-text">{{ __('Reports') }}</span>
                            </a>
                            <div class="collapse {{ request()->is('*channel-report*') ? ' show' : '' }}" id="navbar-maps">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item {{ request()->is('*channel-report') ? ' active' : '' }}">
                                        <a href="{{route('admin.report.channel')}}" class="nav-link">
                                            {{ __('By Channel') }}
                                        </a>
                                    </li>
                                    <li class="nav-item {{ request()->is('*reports/category') ? ' active' : '' }}">
                                        <a href="{{route('admin.report.category')}}" class="nav-link">
                                            <span class="item-name">{{ __('By Category') }}</span>
                                        </a>
                                    </li>
                                    <li class="nav-item {{ request()->is('*reports/sentiment') ? ' active' : '' }}">
                                        <a href="{{route('admin.tickets.index','on-hold')}}" class="nav-link">
                                            <span class="item-name">{{ __('Sentiment Analysis') }}</span>
                                        </a>
                                    </li>
                                    {{-- <li class="nav-item {{ request()->is('*ticket/closed') ? ' active' : '' }}">
                                        <a href="{{route('admin.tickets.index','closed')}}" class="nav-link">
                                            <span class="item-name">{{ __('Closed') }}</span>
                                        </a>
                                    </li> --}}
                                </ul>
                            </div>
                        </li>
                    @endcan
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/admin/partials/topnav.blade.php
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
                <div class="form-group mb-0">
                    <div class="input-group input-group-alternative input-group-merge">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-search"></i></span>
                        </div>
                        <input class="form-control" placeholder="Search" type="text">
                    </div>
                </div>
                <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </form>
            <ul class="navbar-nav align-items-center ml-md-auto">
                <li class="nav-item d-xl-none">
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
                <li class="nav-item d-sm-none">
                    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                        <i class="ni ni-zoom-split-in"></i>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-flag"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-md dropdown-menu-right py-0 overflow-hidden">
                        <div class="px-3 py-2">
                            <h6 class="text-sm text-primary m-0">{{ __('Choose Language') }}</h6>
                        </div>
                        <div class="list-group list-group-flush">
                            @foreach(Auth::user()->languages() as $code)
                                <a href="{{ route('admin.lang.update',$code) }}" class="list-group-item list-group-item-action py-1">
                                    <p class="mb-0 text-sm {{ (Auth::user()->currantLang() == $code) ? 'font-weight-bold' : '' }}">{{ Str::upper($code) }}</p>
                                </a>
                            @endforeach
                        </div>
                        @can('lang-manage')
                            <a href="{{route('admin.lang.index',[Auth::user()->currantLang()])}}" class="dropdown-item text-center text-primary font-weight-bold py-2">{{ __('Manage Languages') }}</a>
                        @endcan
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav align-items-center ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                          <span class="avatar avatar-sm rounded-circle">
                            <img alt="Image placeholder" src="{{ Auth::user()->avatarlink }}">
                          </span>
                            <div class="media-body ml-2 d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">{{ Auth::user()->name }}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <a href="{{ Auth::user()->profilelink }}" class="dropdown-item">
                            <i class="ni ni-settings-gear-65"></i>
                            <span>{{ __('Account Settings') }}</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ route('logout') }}" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>{{ __('Sign Out') }}</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>