routes/web.php
<?php
Route::get('/', 'HomeController@index')->name('main');

Route::get('ticket/{id}', ['as' => 'home.view','uses' =>'HomeController@view']);
Route::post('ticket/{id}', ['as' => 'home.reply','uses' =>'HomeController@reply']);

Route::get('faq', ['as' => 'faq','uses' =>'HomeController@faq']);
Route::get('search', ['as' => 'search','uses' =>'HomeController@search']);
Route::post('search', ['as' => 'ticket.search','uses' =>'HomeController@ticketSearch']);


Route::name('admin.')->prefix('admin')->middleware('auth')->group(function() {
    Route::get('dashboard', 'DashboardController')->name('dashboard');

    Route::get('users/roles', 'UserController@roles')->name('users.roles');
    Route::resource('users', 'UserController', [
        'names' => [
            'index' => 'users'
        ]
    ]);
    Route::get('lang/clear',['as' => 'lang.clear','uses' =>'LanguageController@clear']);

    Route::get('lang/create',['as' => 'lang.create','uses' =>'LanguageController@create']);
    Route::post('lang/create',['as' => 'lang.store','uses' =>'LanguageController@store']);
    Route::get('lang/{lang}',['as' => 'lang.index','uses' =>'LanguageController@index']);
    Route::post('lang/{lang}',['as' => 'lang.store.data','uses' =>'LanguageController@storeData']);

    Route::get('lang/change/{lang}',['as' => 'lang.update','uses' =>'LanguageController@update']);

    Route::get('ticket/create',['as' => 'tickets.create','uses' =>'TicketController@create']);
    Route::post('ticket',['as' => 'tickets.store','uses' =>'TicketController@store']);
    Route::get('ticket/{status?}',['as' => 'tickets.index','uses' =>'TicketController@index']);
    Route::get('ticket/{id}/edit',['as' => 'tickets.edit','uses' =>'TicketController@editTicket']); //escalate
    Route::get('ticket/{id}/escalate',['as' => 'tickets.escalate','uses' =>'TicketController@escalateTicket']); //escalate
    Route::delete('ticket/{id}/destroy',['as' => 'tickets.destroy','uses' =>'TicketController@destroy']);
    Route::delete('ticket-attachment/{tid}/destroy/{id}',['as' => 'tickets.attachment.destroy','uses' =>'TicketController@attachmentDestroy']);
    Route::put('ticket/{id}/update',['as' => 'tickets.update','uses' =>'TicketController@updateTicket']);

    Route::get('category/create',['as' => 'category.create','uses' =>'CategoryController@create']);
    Route::post('category',['as' => 'category.store','uses' =>'CategoryController@store']);
    Route::get('category',['as' => 'category','uses' =>'CategoryController@index']);
    Route::get('category/{id}/edit',['as' => 'category.edit','uses' =>'CategoryController@edit']);
    Route::delete('category/{id}/destroy',['as' => 'category.destroy','uses' =>'CategoryController@destroy']);
    Route::put('category/{id}/update',['as' => 'category.update','uses' =>'CategoryController@update']);

    Route::get('faq/create',['as' => 'faq.create','uses' =>'FaqController@create']);
    Route::post('faq',['as' => 'faq.store','uses' =>'FaqController@store']);
    Route::get('faq',['as' => 'faq','uses' =>'FaqController@index']);
    Route::get('faq/{id}/edit',['as' => 'faq.edit','uses' =>'FaqController@edit']);
    Route::delete('faq/{id}/destroy',['as' => 'faq.destroy','uses' =>'FaqController@destroy']);
    Route::put('faq/{id}/update',['as' => 'faq.update','uses' =>'FaqController@update']);

//    Route::('category',['as' => 'category','uses' =>'CategoryController@index']);
    Route::post('ticket/{id}/conversion',['as' => 'conversion.store','uses' =>'ConversionController@store']);
    Route::post('ticket/{id}/note',['as' => 'note.store','uses' =>'TicketController@storeNote']);

    Route::get('setting',['as' => 'setting','uses' =>'UserController@setting']);
    Route::post('setting',['as' => 'setting.store','uses' =>'UserController@save_setting']);

    Route::get('business_units',['as' => 'buss_units','uses' =>'bussUnitsController@buss_units']);

    Route::post('ticket/{id}/update_escalation',['as' => 'escalation.update','uses' =>'TicketController@update_escalation']);

    Route::get('channel-report',['as' => 'report.channel','uses' =>'ReportController@channelShow']);
    Route::get('category-report',['as' => 'report.category','uses' =>'ReportController@categoryShow']);

    Route::post('channel-check',['as' => 'report.check','uses' =>'ReportController@checkChannel']);
    Route::post('category-check',['as' => 'report.catcheck','uses' =>'ReportController@checkCategory']);
    // Message Route
    Route::get('chat',['as' => 'chats','uses' =>'MessageController@index']);
    Route::get('message/{id}',['as' => 'message','uses' => 'MessageController@getMessage']);
    Route::post('message', 'MessageController@sendMessage');
    // End Message Route

});

Route::get('home', ['as' => 'home','uses' =>'HomeController@index']);

Route::prefix('sbu/sbu-ref={sbu_id}/')->group(function () {

    Route::get('home', ['as' => 'home','uses' =>'HomeController@new_ticket_index']);
    Route::post('home', ['as' => 'home.store','uses' =>'HomeController@store']);
    });

Route::get('get_message',['as' => 'get_message','uses' => 'MessageController@getFloatingMessage']);
Route::post('message_form',['as' => 'chat_form.store','uses' =>'MessageController@store']);
Route::post('floating_message', 'MessageController@sendFloatingMessage');

Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Auth::routes(['verify' => true]);

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Ticket;
use Illuminate\Http\Request;

class ReportController extends Controller
{
    //

    public function channelShow(){
        // $channels = Ticket::groupBy('channel');
        return view('admin.report.create');
    }

    public function categoryShow(){
         $categories = Category::all();
        return view('admin.report.category.create',[
            'categories' => $categories
        ]);
    }



    public function checkChannel(Request $request){
       $all_channel_tickets = Ticket::where('channel',$request->input('channel'))->get();
       $channel = 'Report by Channel: '.$request->input('channel');
       return view('admin.report.index')->with('tickets',$all_channel_tickets)
                                        ->with('channel',$channel);
    }

    public function checkCategory(Request $request){
        $all_channel_tickets = Ticket::where('category',$request->input('category'))->get();
        $channel = 'Report by  Category: '.$request->input('category');
        return view('admin.report.category.index')->with('tickets',$all_channel_tickets)
                                         ->with('category',$channel);
     }
}

resources/views/admin/report/create.blade.php
@extends('layouts.admin-master')

@section('title')
    {{ __('Report By Channel') }}
@endsection

@section('breadcrumb')
    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i> {{ __('Dashboard') }}</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.users') }}">{{ __('Report') }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header"><h4>{{ __('Report By Channel') }}</h4></div>
                <div class="card-body">
                    <br><br>
                    <form method="post" class="needs-validation" action="{{route('admin.report.check')}}" enctype="multipart/form-data">
                        @csrf



                        <div class="form-group row mb-4">
                            <label class="col-form-label form-control-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Channel') }}</label>
                            <div class="col-sm-12 col-md-7">
                                <select class="form-control select2" name="channel" required>
                                   <option>Please select channel</option>
                                   <option value='Web'>CMS Site - Web</option>
                                   <option value="Twitter">From Twitter</option>
                                   <option value="Whatsapp">From Whatsapp</option>
                                   <option value="Facebook">From Facebook</option>
                                </select>
                            </div>
                        </div>




                        <div class="form-group row mb-4">
                            <label class="col-form-label form-control-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button class="btn btn-primary"><span>{{ __('Generate') }}</span></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/report/index.blade.php
@extends('layouts.admin-master')

@section('title')
    {{ $channel }}
@endsection

@section('breadcrumb')
    <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i> {{ __('Dashboard') }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
    </ol>
@endsection

@section('actions')
    @can('create-tickets')
        <a href="{{route('admin.tickets.create')}}" class="btn btn-sm btn-neutral">{{ __('Add') }} <i class="fa fa-plus-circle"></i></a>
    @endcan
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12 col-md-12">
            @if(session()->has('ticket_id') || session()->has('smtp_error'))
                <div class="alert alert-primary">
                    @if(session()->has('ticket_id'))
                        {!! Session::get('ticket_id') !!}
                        {{ Session::forget('ticket_id') }}
                    @endif
                    @if(session()->has('smtp_error'))
                        {!! Session::get('smtp_error') !!}
                        {{ Session::forget('smtp_error') }}
                    @endif
                </div>
            @endif
        </div>
        <div class="col-lg-12 col-md-12">
            <div class="card o-hidden mb-4">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="datatable-basic" class="table dataTable-collapse text-center">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">{{ __('Ticket ID') }}</th>
                                <th scope="col">{{ __('Name') }}</th>
                                <th scope="col">{{ __('Email') }}</th>
                                <th scope="col">{{ __('Subject') }}</th>

                                <th scope="col">{{ __('Channel') }}</th>
                                <th scope="col">{{ __('Status') }}</th>
                                <th scope="col">{{ __('Assignee') }}</th>
                                <th scope="col">{{ __('Resolution Stage') }}</th>
                                <th scope="col">{{ __('Created') }}</th>
                                <th scope="col">{{ __('Expected Close Date') }}</th>
                                <th scope="col">{{ __('Action') }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($tickets as $index => $ticket)
                                <tr>
                                    <th scope="row">{{++$index}}</th>
                                    <td>{{$ticket->ticket_id}}</td>
                                    <td>{{$ticket->name}}</td>
                                    <td>{{$ticket->email}}</td>
                                    <td>{{$ticket->subject}}</td>
                                    {{-- <td><span class="badge badge-success" style="background: {{$ticket->color}}">{{$ticket->category_name}}</span></td> --}}
                                    <td>{{$ticket->channel}}</td>
                                    <td><span class="badge @if($ticket->status == 'In Progress')badge-warning @elseif($ticket->status == 'On Hold') badge-danger @else badge-success @endif">{{__($ticket->status)}}</span></td>
                                    <td>{{$ticket->ticket_assignee->name}}</td>
                                    <td>{{$ticket->ticket_level->Description}}</td>
                                    <td>{{$ticket->created_at->diffForHumans()}}</td>
                                    <td>{{date('d M y', strtotime($ticket->must_close_at))}}</td>
                                    <td>
                                        @can('reply-tickets')
                                            <a class="text-primary mr-4 " title="{{ __('Update Ticket') }}" href="{{route('admin.tickets.edit',$ticket->id)}}"><i class="fa fa-reply font-weight-bold"></i></a>
                                        @endcan
                                        @can('edit-tickets')
                                            <a class="text-danger mr-2" title="{{ __('Delete') }}" onclick="(confirm('Are You Sure?')?(document.getElementById('user-form-{{$ticket->id}}').submit()):'');"><i class="fa fa-trash font-weight-bold"></i></a>
                                            <form method="post" id="user-form-{{$ticket->id}}" action="{{route('admin.tickets.destroy',$ticket->id)}}">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection